/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.sourceweb.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.struts.ActionSupport;



import cn.sourceweb.form.LoginForm;
import cn.sourceweb.po.User;
import cn.sourceweb.service.UserService;


/** 
 * MyEclipse Struts
 * Creation date: 11-06-2014
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends ActionSupport{
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		ActionForward forword = mapping.getInputForward();
		String userNameString = loginForm.getUserName();
		String passwordString = loginForm.getPassword();
		UserService service = (UserService)getWebApplicationContext().getBean("UserService");
		User userFromDB = service.getUserByuserName(userNameString);
		if(userFromDB!=null){
			if(passwordString.equals(userFromDB.getPassword()))
				forword = mapping.findForward("success");
			else {
				forword = mapping.findForward("fail");
			}
		}
		return forword;
	}

	
}